# Docker
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'Azure subscription 1 (11e3388f-0f40-489b-801c-ff228736012a)'
    appName: 'HelloStackoverflow'
    containers: 'HelloStackoverflow'
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
