# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - HelloStackoverflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_ce87ae2ea9b344de9cc84ecd2385993e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_36d1c87047c649c1a58447031f61b044 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ce87ae2ea9b344de9cc84ecd2385993e }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'HelloStackoverflow'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_621379e0568446f0a4f1e8f5308997b6 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ce87ae2ea9b344de9cc84ecd2385993e }}/appsvc/staticsite:${{ github.sha }}'